### ISSUE TITLE
Failed registering comparison function for counter attribute Daily-Session-Time: Attribute 'Daily-Session-Time' already exists

### ISSUE THREAD

**Issue by Ara4Sh** [FreeRADIUS/freeradius-server#1200] opened 2015-08-25 12:15 UTC
Hello
i have a problem with a counter named Daily-Session-Time
first that was tried to load give me this error message : 
```
Tue Aug 25 16:39:22 2015 : Error: /etc/freeradius/mods-enabled/sqlcounter[94]: Counter attribute Daily-Session-Time MUST be integer64
Tue Aug 25 16:39:22 2015 : Error: /etc/freeradius/mods-enabled/sqlcounter[94]: Instantiation failed for module "dailycounter"
```

in dictionary file i edit the line and set integer64 for Daily-Session-Time
```
ATTRIBUTE       Daily-Session-Time      3000    integer64
```
and now the error is : 
```
Tue Aug 25 16:40:59 2015 : Error: /etc/freeradius/mods-enabled/sqlcounter[94]: Failed registering comparison function for counter attribute Daily-Session-Time: Attribute 'Daily-Session-Time' already exists
Tue Aug 25 16:40:59 2015 : Error: /etc/freeradius/mods-enabled/sqlcounter[94]: Instantiation failed for module "dailycounter"
```
this is dailycounter in /etc/freeradius/mods-config/sql/counter/mysql :
```
query = "\
        SELECT IFNULL(SUM(acctsessiontime),0) \
        FROM radacct \
        WHERE username = '%{${key}}' \
        AND compid = '%{Huntgroup-Name}' \
        AND acctstarttime BETWEEN FROM_UNIXTIME('%b') AND FROM_UNIXTIME('%e')"
```

freeradius version : 
```
freeradius: FreeRADIUS Version 3.1.0 (git #188a101), for host x86_64-pc-linux-gnu, built on Aug 17 2014 at 14:27:53
```

if you need further information tell me to provide for you

**Comment by jpereira** [comment] 2015-08-25 13:47
@Ara4Sh Use the latest version from the repository.

**Comment by arr2036** [comment] 2015-08-25 13:50
Yeah all that code was rewritten after that commit and your last build.  It probably works now...

**Comment by arr2036** [comment] 2015-08-25 16:02
Can't reproduce with current v3.1.x HEAD so closing this issue.

**Closed by arr2036** 2015-08-25 16:02 UTC
