### ISSUE TITLE
FreeRadius 3.0.8 Unknown Seg Fault 

### ISSUE THREAD

**Issue by cteague711** [FreeRADIUS/freeradius-server#1063] opened 2015-06-18 13:36 UTC
radiusd: FreeRADIUS Version 3.0.8, for host x86_64-unknown-linux-gnu, built on Jun 17 2015 at 01:06:45

2.6.32-504.1.3.el6.x86_64 #1 SMP Fri Oct 31 11:37:10 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

Red Hat Enterprise Linux Server release 6.2 (Santiago)

Logs do not contain any reason for why FR terminates. Seg fault occurs at least once every 24-48 hours. SNMP monitoring of Linux OS indicates memory consumption is linear and once used memory hits 100% a seg fault will occur.

Utilized features:

802.1x EAP-TTLS (MS-CHAPv2), PEAP (MS-CHAPv2), EAP-SIM, EAP-AKA
RLM-Cache
EAP Resumption
mySQL Database
```
GDB Output

  11 Thread 5256  0x0000003a2e6e1453 in ?? ()
  10 Thread 22752  0x0000003a2ea0d930 in ?? ()
  9 Thread 22759  0x0000003a2ea0d930 in ?? ()
  8 Thread 22751  0x0000003a2ea0d930 in ?? ()
  7 Thread 22760  0x0000003a2ea0d930 in ?? ()
  6 Thread 22753  0x0000003a2ea0d930 in ?? ()
  5 Thread 22758  0x0000003a2ea0d930 in ?? ()
  4 Thread 22754  0x0000003a2ea0d930 in ?? ()
  3 Thread 22756  0x0000003a2ea0d930 in ?? ()
  2 Thread 22755  0x0000003a2ea0d930 in ?? ()
* 1 Thread 22757  0x000000000044d282 in identity_is_safe (identity=0x0) at src/main/tls.c:102

Thread 11 (Thread 5256):
#0  0x0000003a2e6e1453 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 10 (Thread 22752):
#0  0x0000003a2ea0d930 in ?? ()
No symbol table info available.
#1  0x000000000067bbd0 in ?? ()
No symbol table info available.
#2  0x0000000000437cd4 in request_handler_thread (arg=0x8eaad40) at src/main/threads.c:667
        self = 0x8eaad40
#3  0x0000003a2ea079d1 in ?? ()
No symbol table info available.
#4  0x00007fde9b72b700 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 9 (Thread 22759):
#0  0x0000003a2ea0d930 in ?? ()
No symbol table info available.
#1  0x000000000067bbd0 in ?? ()
No symbol table info available.
#2  0x0000000000437cd4 in request_handler_thread (arg=0x9eab580) at src/main/threads.c:667
        self = 0x9eab580
#3  0x0000003a2ea079d1 in ?? ()
No symbol table info available.
#4  0x00007fde97124700 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 8 (Thread 22751):
#0  0x0000003a2ea0d930 in ?? ()
No symbol table info available.
#1  0x000000000067bbd0 in ?? ()
No symbol table info available.
#2  0x0000000000437cd4 in request_handler_thread (arg=0x8551110) at src/main/threads.c:667
        self = 0x8551110
#3  0x0000003a2ea079d1 in ?? ()
No symbol table info available.
#4  0x00007fde9c12c700 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 7 (Thread 22760):
#0  0x0000003a2ea0d930 in ?? ()
No symbol table info available.
#1  0x000000000067bbd0 in ?? ()
No symbol table info available.
#2  0x0000000000437cd4 in request_handler_thread (arg=0x7446590) at src/main/threads.c:667
        self = 0x7446590
#3  0x0000003a2ea079d1 in ?? ()
No symbol table info available.
#4  0x00007fde96723700 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 6 (Thread 22753):
#0  0x0000003a2ea0d930 in ?? ()
No symbol table info available.
#1  0x000000000067bbd0 in ?? ()
No symbol table info available.
#2  0x0000000000437cd4 in request_handler_thread (arg=0xa1eff80) at src/main/threads.c:667
        self = 0xa1eff80
#3  0x0000003a2ea079d1 in ?? ()
No symbol table info available.
#4  0x00007fde9ad2a700 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 5 (Thread 22758):
#0  0x0000003a2ea0d930 in ?? ()
No symbol table info available.
#1  0x000000000067bbd0 in ?? ()
No symbol table info available.
#2  0x0000000000437cd4 in request_handler_thread (arg=0x8eaa870) at src/main/threads.c:667
        self = 0x8eaa870
#3  0x0000003a2ea079d1 in ?? ()
No symbol table info available.
#4  0x00007fde97b25700 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 4 (Thread 22754):
#0  0x0000003a2ea0d930 in ?? ()
No symbol table info available.
#1  0x000000000067bbd0 in ?? ()
No symbol table info available.
#2  0x0000000000437cd4 in request_handler_thread (arg=0x590be20) at src/main/threads.c:667
        self = 0x590be20
#3  0x0000003a2ea079d1 in ?? ()
No symbol table info available.
#4  0x00007fde9a329700 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 3 (Thread 22756):
#0  0x0000003a2ea0d930 in ?? ()
No symbol table info available.
#1  0x000000000067bbd0 in ?? ()
No symbol table info available.
#2  0x0000000000437cd4 in request_handler_thread (arg=0x7ec3620) at src/main/threads.c:667
        self = 0x7ec3620
#3  0x0000003a2ea079d1 in ?? ()
No symbol table info available.
#4  0x00007fde98f27700 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (Thread 22755):
#0  0x0000003a2ea0d930 in ?? ()
No symbol table info available.
#1  0x000000000067bbd0 in ?? ()
No symbol table info available.
#2  0x0000000000437cd4 in request_handler_thread (arg=0xa1f0260) at src/main/threads.c:667
        self = 0xa1f0260
#3  0x0000003a2ea079d1 in ?? ()
No symbol table info available.
#4  0x00007fde99928700 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (Thread 22757):
#0  0x000000000044d282 in identity_is_safe (identity=0x0) at src/main/tls.c:102
        c = 0 '\000'
#1  0x000000304e621b8a in ?? ()
No symbol table info available.
#2  0x00007fde98524260 in ?? ()
No symbol table info available.
#3  0x00000000ffffffff in ?? ()
No symbol table info available.
#4  0x00007fde98524220 in ?? ()
No symbol table info available.
#5  0x000000005581b40b in ?? ()
No symbol table info available.
#6  0x00007fde98524240 in ?? ()
No symbol table info available.
#7  0x000000000000000b in ?? ()
No symbol table info available.
#8  0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by arr2036** [comment] 2015-06-18 13:42
Please use v3.0.x HEAD. There was a severe memory leak which has now been fixed.

**Comment by cteague711** [comment] 2015-06-18 13:45
Does the output from gdb match the memory leak which was fixed? I will update to the latest release and lab and test. Thanks Arran.

**Comment by arr2036** [comment] 2015-06-18 13:47
It's not possible to tell:

a) Because you've not installed debugging symbols. Those ?? mean as much to me as they do to you.
b) Because it's not possible to diagnose memory leaks with GDB.

If I could categorically say, no, this memory leak is definitely not the cause of your issue, then I wouldn't have told you to upgrade :)

**Comment by arr2036** [comment] 2015-06-23 18:59
Closing this until we receive additional information.

**Closed by arr2036** 2015-06-23 18:59 UTC
