### ISSUE TITLE
Memory leak in rlm_files

### ISSUE THREAD

**Issue by dddpaul** [FreeRADIUS/freeradius-server#1475] opened 2015-12-30 08:16 UTC
Hi.

I've used a quite large "authorize" file - about 116 thousand entries (~50 Mbytes). When radiusd is started it consumes about 320 Mbytes.

Then I update my large "authorize" file (change one symbol is enough) and run "pkill -1 radiusd". Updated file is reloaded and boom! - radiusd consumes 626 MBytes now.

After that every "pkill -1 radiusd" adds about 300 megs to radiusd memory consumption. The interesting thing is that you haven't got to update "authorize" file now. File detected as updated and reloaded regardless of being actually updated or not.

Radiusd logs:
```
Received HUP signal                          
 Module: Reloaded module "files"             
HUP - Files loaded by a module have changed. 
Ready to process requests                    
```

It grows and grows till some limit (always different - 1.8 Gbytes, 3 Gbytes etc). This time it grows till 3.7 Gbytes:

```
root      8216  1.7 23.1 3983664 3776328 ?     Sl   10:47   0:15 /usr/local/sbin/radiusd -f -l stdout -x
```

The server behaves steadily, no performance drawback was detected.

This memory leak exposes on these versions: 3.0.10 release, 3.0.x branch and 3.1.x branch.

**Comment by alandekok** [comment] 2015-12-30 14:40
The server keeps old versions of the file around, because active requests may still be using them.  You should see it cleanup up the memory after 30-60 seconds.

I can't reproduce this here.  If the `authorize` file hasn't changed, then it doesn't reload the `files` module.

And on a more general note, if you have 100K+ entries in the `authorize` file, you should really be using a database instead.  Databases support live changes.

**Comment by arr2036** [comment] 2016-01-04 04:49
Closing for now.  Will re-open if @dddpaul can produce instructions for reproducing.

**Closed by arr2036** 2016-01-04 04:49 UTC
