### ISSUE TITLE
ARM docker builds

### ISSUE THREAD

**Issue by varac** [FreeRADIUS/freeradius-server#3513] opened 2020-07-02 19:55 UTC
Please provide ARM / ARM64 builds of the [freeradius server docker image](https://hub.docker.com/r/freeradius/freeradius-server/tags). ARM architecture is getting more and more popular (raspberry pi i.e.) and it would be great to have pre-built images on docker hub. Thanks !

**Comment by shivamb** [comment] 2020-07-31 15:24
I would be happy to get pre built images for ARM

**Comment by mcnewton** [comment] 2021-05-12 19:15
Duplicate of #2780

**Closed by mcnewton** 2021-05-12 19:15 UTC

**Comment by helmiaqmarr** [comment] 2021-10-04 09:02
Hi , is it freeradius is compatible with Linux ARM64 infrastructure ?
