### ISSUE TITLE
radius server not response when encounter special character

### ISSUE THREAD

**Issue by jiangjianping** [FreeRADIUS/freeradius-server#1726] opened 2016-09-13 11:45 UTC
Version: freeradius-server-3.0.11
Environment: gnugk->radius server(local relay)->radius accouting server 
Module: Relay Server: Accouting with detail, Accounting Server: Accouting with linelog

Issue: Special characters（UTF-8 other than Ascii) wil cause radius server not response to accounting request

Accounting record on Relay Server:
```
Tue Sep  6 19:50:10 2016
        Acct-Status-Type = Stop
        NAS-IP-Address = 123.59.170.71
        NAS-Identifier = "GnuGk"
        NAS-Port-Type = Virtual
        Service-Type = Login-User
        Acct-Session-Id = "57c11224000006a2"
        User-Name = "諞\275丿\255"
        Framed-IP-Address = 111.23.46.106
        Acct-Session-Time = 38
        Calling-Station-Id = "諞\275丿\255"
        Called-Station-Id = "1935"
        h323-conf-id = "h323-conf-id=E04D5EB6 4C02001F 14FDCE5 BA6BC861"
        h323-gw-id = "h323-gw-id=GnuGk"
        h323-call-origin = "h323-call-origin=proxy"
        h323-call-type = "h323-call-type=VoIP"
        h323-setup-time = "h323-setup-time=2016-09-06 19:49:32 UTC+0800"
        h323-connect-time = "h323-connect-time=2016-09-06 19:49:32 UTC+0800"
        h323-disconnect-time = "h323-disconnect-time=2016-09-06 19:50:10 UTC+0800"
        h323-disconnect-cause = "h323-disconnect-cause=10"
        release-source = "release-source=1"
        gw-rxd-cgn = "preferred-codec=Unknown"
        gw-final-xlated-cgn = "rewritten-e164-num=1935"
        Cisco-AVPair = "h323pddtime=0"
        Cisco-AVPair = "h323ringtime=0"
        Cisco-AVPair = "h323routeattempts=0"
        Cisco-AVPair = "h323_rtp_proxy=1"
        Cisco-AVPair = "RTP_source_IP=123.59.170.86"
        Cisco-AVPair = "RTP_destination_IP=111.23.46.106"
        Cisco-AVPair = "RTCP_source_packet_count=0"
        Cisco-AVPair = "RTCP_source_packet_lost=0"
        Cisco-AVPair = "RTCP_source_jitter=0|0|0"
        Cisco-AVPair = "RTCP_destination_packet_count=0"
        Cisco-AVPair = "RTCP_destination_packet_lost=0"
        Cisco-AVPair = "RTCP_destination_jitter=0|0|0"
        h323-remote-address = "h323-remote-address=123.59.170.95"
        Cisco-AVPair = "h323-ivr-out=h323-call-id:373B5EB6 4C02001F 14FDCE5 BA6BC861"
        Acct-Delay-Time = 0
        Realm = "radrelay"
        Module-Failure-Message = "Failing proxied request for user \"諞\275丿\255\", due to lack of any response from home server 10.10.10.22 port 1813"
        Freeradius-Proxied-To = 10.10.10.22
        Timestamp = 1473162610



Linelog Configuration:
         Accounting-Request {
        Stop = "CDR:type=h323;%{h323-connect-time};%{h323-disconnect-time};duration=%{Acct-Session-Time};sessionid=%{Acct-Session-Id};caller=%{Calling-Station-
Id};callee=%{Called-Station-Id};sourceip=%{Framed-IP-Address}"
           }


Radius Accouting Server Halted at (with -X option:)


(131) # Executing section accounting from file /opt/zjcloud/conf/raddb/radiusd.conf
(131)   accounting {
(131) linelog: EXPAND Accounting-Request.%{%{Acct-Status-Type}:-unknown}
(131) linelog:    --> Accounting-Request.Stop
(131) linelog: EXPAND /var/zjcloud/CDR/cdr-%Y%m%d%H
(131) linelog:    --> /var/zjcloud/CDR/cdr-2016091316
```

**Comment by arr2036** [comment] 2016-09-13 11:55
So... where does it stop?  Can you provide a backtrace?

**Comment by arr2036** [comment] 2016-09-18 03:01
@alandekok did you figure out a fix for this one?

**Comment by alandekok** [comment] 2016-09-18 13:36
We need a root cause analysis, not something that "works around" the problem.

**Comment by alandekok** [comment] 2016-09-25 14:52
I've pushed a fix for the linelog_escape function.  If we can't get a root cause (i.e. gdb backtrace), then we might as well close this issue.

**Closed by alandekok** 2016-09-25 14:52 UTC
