### ISSUE TITLE
segfault when rlm_always is missing from modules section

### ISSUE THREAD

**Issue by jimdigriz** [FreeRADIUS/freeradius-server#1911] opened 2017-02-13 17:17 UTC
# Issue type
- [X] Defect - Crash or memory corruption.
- [ ] Defect - Non compliance with a standards document, or incorrect API usage.
- [ ] Defect - Unexpected behaviour (obvious or verified by project member).
- [ ] Feature request.

# Defect/Feature description
## How to reproduce issue

Comment out from `modules{}` the link to `rlm_always`.

## Full backtrace from LLDB or GDB
```
$ gdb -arg ./build/bin/local/radiusd -X -d raddb -n radrelay
(gdb) run
[snipped]
Debug : radrelay: #### Loading Clients ####
Info  : Found debugger attached
Warn  : No 'thread pool {..}' found.  Server will be single threaded
Debug :   # Loaded module "proto_detail"
Debug : listen {
Debug :         type = "detail"
Debug :   listen {
Debug :         filename = "/usr/local/var/log/radius/radacct/detail"
Debug :         load_factor = 90
Debug :         poll_interval = 1
Debug :         retry_interval = 30
Debug :         one_shot = no
Debug :         track = no
Debug :   }
Debug : }
Debug : radrelay: #### Loading modules ####
Debug :  modules {
Debug :   instantiate {
Debug :   }
Debug :  } # modules

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7963b12 in rbtree_walk (tree=0x0, order=RBTREE_IN_ORDER, compare=0x7ffff7ba4415 <_cf_data_walk_cb>, 
    context=0x7fffffffe4e0) at src/lib/rbtree.c:709
709             if (tree->root == NIL) return 0;
(gdb) bt
#0  0x00007ffff7963b12 in rbtree_walk (tree=0x0, order=RBTREE_IN_ORDER, 
    compare=0x7ffff7ba4415 <_cf_data_walk_cb>, context=0x7fffffffe4e0) at src/lib/rbtree.c:709
#1  0x00007ffff7ba4504 in _cf_data_walk (cs=0x9f2f90, type=0x467eb7 "module_instance_t", 
    cb=0x427aad <_module_instantiate>, ctx=0x0) at src/main/conffile.c:4232
#2  0x0000000000427d18 in modules_instantiate (root=0x9dd440) at src/main/modules.c:752
#3  0x00000000004292b3 in main (argc=6, argv=0x7fffffffe6a8) at src/main/radiusd.c:541
```

**Comment by alandekok** [comment] 2017-02-13 18:58
I can't reproduce it here, but it is a bug.  I've pushed a fix.

**Closed** 2017-02-13 18:58 UTC
