### ISSUE TITLE
make deb fails with json-c dependency on Debian Buster

### ISSUE THREAD

**Issue by shahn** [FreeRADIUS/freeradius-server#4058] opened 2021-04-15 02:58 UTC
# Issue type

***

- Defect - Unexpected behaviour (obvious or verified by project member).

`make deb` is satisfied with the installed dependencies, but then fails to build freeradius-json.so which in turn leads to a linking error

### How to reproduce the issue

On Debian Buster after cloning master, on commit 415c89cd7722223bc3298b078d3bfbbf456d702e, I installed the following packages:
```
ii  libjson-c-dev:amd64                   0.12.1+ds-2+deb10u1           amd64        JSON manipulation library - development files
ii  libjson-c3:amd64                      0.12.1+ds-2+deb10u1           amd64        JSON manipulation library - shared library
```

`make deb` ultimately fails with
```
dh_install --sourcedir=/home/debbuild/freeradius-server/debian/tmp -p libfreeradius4
dh_install: Cannot find (any matches for) "usr/lib/freeradius/libfreeradius-json.so" (tried in /home/debbuild/freeradius-server/debian/tmp, debian/tmp)
```

after failing to build freeradius-json:
```
=== configuring in ./src/lib/json (/home/debbuild/freeradius-server/./src/lib/json)
configure: running /bin/bash ./configure --disable-option-checking '--prefix=/usr'  '--build' 'x86_64-linux-gnu' '--disable-developer' '--disable-openssl-version-check' '--exec-prefix=/usr' '--mandir=/usr/share/man' '--sysconfdir=/etc' '--libdir=/usr/lib/freeradius' '--datadir=/usr/share' '--localstatedir=/var' '--with-raddbdir=/etc/freeradius' '--with-logdir=/var/log/freeradius' '--with-large-files' '--with-udpfromto' '--without-rlm_eap_tnc' '--with-rlm_sql_postgresql_lib_dir=/usr/lib/x86_64-linux-gnu' '--with-rlm_sql_postgresql_include_dir=/usr/include/postgresql' '--without-rlm_eap_ikev2' '--without-rlm_sql_oracle' '--without-rlm_sql_unixodbc' '--with-systemd' '--enable-reproducible-builds' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/home/debbuild/freeradius-server=. -fstack-protector-strong -Wformat -Werror=format-security -O2' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/home/debbuild/freeradius-server=. -fstack-protector-strong -Wformat -Werror=format-security' --cache-file=../../../config.cache --srcdir=.
configure: loading cache ../../../config.cache
checking for gcc... (cached) gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... (cached) o
checking whether the compiler supports GNU C... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to enable C11 features... (cached) none needed
checking how to run the C preprocessor... (cached) gcc -E
checking for json/json.h... no
checking for json/json.h in /usr/local/include/... no
checking for json/json.h in /opt/include/... no
checking for json-c/json.h... yes
checking for json_object_object_add_ex in -ljson-c... no
checking for json_object_object_add_ex in -ljson-c in /usr/local/lib... no
checking for json_object_object_add_ex in -ljson-c in /opt/lib... no
configure: WARNING: json-c libraries not found. Use --with-jsonc-lib-dir=<path>.
configure: WARNING: silently not building libfreeradius-json.
configure: WARNING: FAILURE: libfreeradius-json requires:  json-c.
configure: updating cache ../../../config.cache
configure: creating ./config.status
config.status: creating all.mk
config.status: creating config.h
```

**Comment by alandekok** [comment] 2021-04-15 12:33
The `master` branch isn't released as a supported version.  It may or may not work on a daily basis.

The short answer is (a) edit the debian rules, or (b) install json-c.

**Closed by alandekok** 2021-04-15 12:33 UTC

**Comment by arr2036** [comment] 2021-04-15 13:07
Well it's more install a version of `json-c >= 0.13`.  There's some API functionality that's in 0.13 that we need around const keys, and avoiding duplicate lookups, and it'd be extremely annoying to work around.  Both ubuntu20 and rhel8 ship with a newer enough json-c library for this not to be an issue, and as @alandekok says, master is currently unreleased, so we're not even sure which operating systems we'll support when it is released.  Given json-c 0.13 is now > 4 years old (2017/11/29), and Buster was released in 2019, I don't have a whole lot of sympathy for its users.

**Comment by shahn** [comment] 2021-04-15 17:31
It seemed to me your Makefile goes to great lengths to detect correct dependencies. I thought perhaps you'd want to warn if the version is too old.

**Comment by arr2036** [comment] 2021-04-15 17:40
Yes and the build system correctly detects that the version of JSON-C is too old, and doesn't bother trying to build its dependents.  The issue is the debian packaging requires that rlm_json and friends be built... The end result is we probably won't provide packages for Debian Buster when v4.0.x is released unless they provide an updated json-c.  If you want to build packages for a modern version of json-c (>= 0.13) locally, `make deb` should work fine for you.

**Comment by arr2036** [comment] 2021-04-16 00:46
The old json packages have now been remove from the control file 505bafc9dc5fdd45a280e7a8da207887c52d501c
